name: Publish

on:
  push:
    tags:
      - '*'

env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  create_nuget:
    name: Create NuGet Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # TODO: verzia
    - run: dotnet pack -c Release /p:Version=${{ github.ref_name }} --output ${{ env.NuGetDirectory }}

    - name: 'Upload Artifacts'
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'nuget'
        path: ${{ env.NuGetDirectory }}
        if-no-files-found: 'error'
        retention-days: 1

  publish_nuget:
    name: Publish NuGet Package
    needs: [create_nuget]
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: '.NET Setup'
        uses: 'actions/setup-dotnet@v4'
        with:
          dotnet-version: '9.0.x'

      - name: 'Download Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: 'nuget'
          path: ${{ env.NuGetDirectory }}

      - name: Prep packages
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: '.NET NuGet Push'
        run: >-
          dotnet nuget push "${{ env.NuGetDirectory }}/*.nupkg"
          --api-key "${{ secrets.GITHUB_TOKEN }}"
          --source "github"
          --skip-duplicate